[package]
name = "obsidian_status"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terminal_size = "0.1.17"
time = {version = "0.3.7", features = ["formatting"]}
battery = "0.7.5"
